# this file launch just the services needed to run waterwheel locally
# launch this using `just up` to develop and debug without having to build the Docker image

version: '3.1'

services:
  amqp:
    image: rabbitmq:3.13-management-alpine
    #environment:
      #- RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit consumer_timeout 86400000 # 24h
    ports:
      - "5672:5672"
      - "8055:15672"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  opa:
    image: openpolicyagent/opa
    ports:
      - "8181:8181"
    volumes:
      - "$PWD/etc/policy:/policy"
    command: ["run", "--server", "-b", "/policy"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
