# alternate Dockerfile which uses the debug build
# (and includes the UI resources as these are not bundled in debug builds)

FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y openssl

ENTRYPOINT ["/usr/bin/waterwheel"]

WORKDIR /root

COPY ui/dist/ /root/ui/dist/
COPY target/debug/waterwheel /usr/bin/

CMD ["--help"]
