# show the readme
help:
    @cat README.md

# update the image tag for the waterweel image
updateTag TAG:
    kustomize edit set image waterwheel=*:{{TAG}}

# build and package waterwheel and load into minikube
package:
    #! /bin/sh
    set -x
    bazel run //:waterwheel_load
    NAME=$(names)
    docker tag waterwheel:local waterwheel:$NAME
    minikube image load waterwheel:$NAME
    kustomize edit set image waterwheel=*:$NAME

# apply all the kubernetes yaml
apply:
    kubectl apply -k .

# create the keypair used for signing sessions
gen-keypair:
    openssl genrsa -out private.pem 2048
    openssl rsa -in private.pem -outform PEM -pubout -out public.pem
