apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: waterwheel-worker

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"] # TODO - limit this a bit
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs:  ["get", "watch", "list", "create", "update", "patch", "delete"] # TODO - limit this a bit

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: waterwheel-worker

subjects:
  - kind: ServiceAccount
    name: default

roleRef:
  kind: Role
  name: waterwheel-worker
  apiGroup: rbac.authorization.k8s.io
