import requests
import uuid
import random

WATERWHEEL_HOST = 'http://localhost:8080'

project = 'autogen_project'

requests.post(WATERWHEEL_HOST + '/api/projects', json={
    'uuid': '9496b838-f77b-410e-9d67-72a320cb00e0',
    'name': project,
    'description': 'a project for the autogenerated test jobs'
})


def template():
    return {
        "uuid": None,
        "project": project,
        "name": None,
        "description": "a generated job",
        "paused": False,
        "triggers": [
            {
                "name": "hourly",
                "start": "2021-03-01T00:00:00Z",
                "period": f'{random.randint(3, 20)}m',
            }
        ],
        "tasks": [
            {
                "name": "step0",
                "docker": {
                    "image": "bash:latest",
                    "args": ["-c", f"sleep {random.randint(1, 10)}s"]
                },
                "depends": [
                    "trigger/hourly"
                ],
            }
        ]
    }


for i in range(1000):

    name = f'job {i}'
    resp = requests.get(WATERWHEEL_HOST + '/api/jobs', params={'name': name, 'project': project})
    if resp.status_code == 404:
        job_id = str(uuid.uuid4())
    else:
        job_id = resp.json()['id']

    job = template()
    job['name'] = name
    job['uuid'] = job_id

    print(f'creating job {i}')
    resp = requests.put(WATERWHEEL_HOST + '/api/jobs', json=job)
    resp.raise_for_status()
