import requests
import uuid

WATERWHEEL_HOST = 'http://localhost:8080'

project = 'autogen_project'

requests.post(WATERWHEEL_HOST + '/api/projects', json={
    'uuid': '9496b838-f77b-410e-9d67-72a320cb00e0',
    'name': project,
    'description': 'a project for the autogenerated test jobs'
})

template = {
    "uuid": None,
    "project": project,
    "name": None,
    "description": "a generated job",
    "triggers": [
        {
            "name": "hourly",
            "start": "2021-03-01T00:00:00Z",
            "period": "1h",
        }
    ],
    "tasks": [
        {
            "name": "step0",
            "depends": [
                "trigger/hourly"
            ],
        }
    ]
}

for i in range(100):

    name = f'job {i}'
    resp = requests.get(WATERWHEEL_HOST + '/api/jobs', params={'name': name, 'project': project})
    if resp.status_code == 404:
        job_id = str(uuid.uuid4())
    else:
        job_id = resp.json()['id']

    job = template.copy()
    job['name'] = name
    job['uuid'] = job_id

    print(f'creating job {i}')
    resp = requests.put(WATERWHEEL_HOST + '/api/jobs', json=job)
    resp.raise_for_status()
