name: Rust

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Build
      run: cargo build

    - name: Clippy
      run: cargo clippy

    - name: Test
      run: cargo test
