name: UI Build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.13.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true

    - name: Build UI
      run: bazel build //ui:ui
